name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-staging
          - ubuntu-20.04
          - ubuntu-20.04-staging
        arch:
          - amd64
          - arm64
    runs-on:
      # Replace with your profile label https://namespace.so/docs/features/faster-github-actions#using-runner-profiles
      - nscloud-${{ matrix.os }}-${{ matrix.arch }}-2x8-with-cache
      - nscloud-cache-tag-yarn-cache
      - nscloud-cache-size-50gb
      - nscloud-exp-container-image-cache
      - nscloud-exp-runner-tool-cache-5gb
    steps:
      - uses: actions/checkout@v3
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: yarn
      - run: yarn
      - run: yarn workspace @project/web-app build
